os: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" .. -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild Plenteum.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%
  - 7z a plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%-windows.zip plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%
  - copy plenteum-testnet-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: plenteum-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: PlenteumTestnetRelease


